function [fitresult, gof] = createFit1(M, N, O)
%CREATEFIT1(M,N,O)
%  Create a fit.
%
%  Data for 'Curve fitting' fit:
%      X Input : M 
%      Y Output: N
%      Weights : O
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Aug-2018 10:51:07!!!!!


%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( M, N, O );

% Set up fittype and options.
ft = fittype( 'poly3' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
%opts.Lower = [0 -Inf -Inf -Inf];
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'N vs. M with O', 'untitled fit 1', 'Location', 'NorthEast' );
% % Label axes
% xlabel M
% ylabel N
% grid on


